DROP DATABASE IF EXISTS bd_cibermall_autentication;
CREATE DATABASE bd_cibermall_autentication;
USE bd_cibermall_autentication;

CREATE TABLE TB_DISTRITO (
    ID_DISTRITO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    COSTO_ENVIO DECIMAL(8,2) DEFAULT 0
);	

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(50) NOT NULL UNIQUE,
    CLAVE VARCHAR(255) NOT NULL,
    ROL VARCHAR(20) NOT NULL,           -- Guardará textos como 'ADMINISTRADOR' o 'VENDEDOR'
    ESTADO INT DEFAULT 1,               -- 1 = Activo, 0 = Inactivo
    NOMBRES VARCHAR(50) NOT NULL,
    APE_PATERNO VARCHAR(50) NOT NULL,
    APE_MATERNO VARCHAR(50) NOT NULL,
    NRO_DOC VARCHAR(15) NOT NULL UNIQUE,
    TELEFONO VARCHAR(9) NOT NULL,
    DIRECCION VARCHAR(50) DEFAULT NULL,
    ID_DISTRITO INT NOT NULL,
    ULTIMO_ACCESO DATETIME DEFAULT NULL,
    FECHA_ACTUALIZACION DATETIME DEFAULT NULL,
    FECHA_REGISTRO DATETIME DEFAULT NULL
);

